#!/usr/bin/env ruby
require 'rubygems'
require "daemons"
require "daemons/rails/config"

config = Daemons::Rails::Config.new("classwatch_daemon", File.dirname(__FILE__) + "/../../")

Daemons.run File.dirname(__FILE__) + "/classwatch_daemon.rb", config.to_hash